### ISSUE TITLE
py39 win64 build broken

### ISSUE THREAD

**Issue by mariusvniekerk** [conda-forge/setuptools-feedstock#178]
Currently failing with

https://dev.azure.com/conda-forge/84710dde-1620-425b-80d0-4cf5baca359d/_apis/build/builds/220132/logs/107

```
2020-10-09T11:46:40.8740773Z (%PREFIX%) %SRC_DIR%>%PREFIX%\python.exe bootstrap.py 
2020-10-09T11:46:40.9339477Z adding minimal entry_points
2020-10-09T11:46:40.9350318Z Regenerating egg_info
2020-10-09T11:46:41.4551459Z running egg_info
2020-10-09T11:46:41.4560766Z writing setuptools.egg-info\PKG-INFO
2020-10-09T11:46:41.4565158Z writing dependency_links to setuptools.egg-info\dependency_links.txt
2020-10-09T11:46:41.4576973Z writing entry points to setuptools.egg-info\entry_points.txt
2020-10-09T11:46:41.4579893Z writing requirements to setuptools.egg-info\requires.txt
2020-10-09T11:46:41.4583172Z writing manifest file 'setuptools.egg-info\SOURCES.txt'
2020-10-09T11:46:41.4746734Z reading manifest file 'setuptools.egg-info\SOURCES.txt'
2020-10-09T11:46:41.4753850Z reading manifest template 'MANIFEST.in'
2020-10-09T11:46:41.5540239Z warning: no files found matching '*.py' under directory 'tests'
2020-10-09T11:46:41.6268732Z writing manifest file 'setuptools.egg-info\SOURCES.txt'
2020-10-09T11:46:43.8871650Z Traceback (most recent call last):
2020-10-09T11:46:43.8872791Z   File "D:\bld\setuptools_1602243830115\work\bootstrap.py", line 59, in <module>
2020-10-09T11:46:43.8874752Z     __name__ == '__main__' and ensure_egg_info()
2020-10-09T11:46:43.8875604Z   File "D:\bld\setuptools_1602243830115\work\bootstrap.py", line 40, in ensure_egg_info
2020-10-09T11:46:43.8877864Z     run_egg_info()
2020-10-09T11:46:43.8878597Z   File "D:\bld\setuptools_1602243830115\work\bootstrap.py", line 56, in run_egg_info
2020-10-09T11:46:43.8880018Z     subprocess.check_call(cmd)
2020-10-09T11:46:43.8880529Z   File "D:\bld\setuptools_1602243830115\_h_env\lib\subprocess.py", line 373, in check_call
2020-10-09T11:46:43.8883375Z     raise CalledProcessError(retcode, cmd)
2020-10-09T11:46:43.8884154Z subprocess.CalledProcessError: Command '['D:\\bld\\setuptools_1602243830115\\_h_env\\python.exe', 'setup.py', 'egg_info']' returned non-zero exit status 3221225477.
```

**Comment by mariusvniekerk** [comment]
Sadly these logs leave much to be desired.  Suggestions @conda-forge/core ?

**Comment by xhochy** [comment]
Just had the same exit code with conda-build in an unrelated settings. In that case the exit code meant "command is missing".

**Comment by mariusvniekerk** [comment]
but which command?

**Comment by xhochy** [comment]
Yes, this weirdly sounds like `python` but I guess that in `egg_info` something is calling an external executable.

**Comment by mbargull** [comment]
Web search for `3221225477`/`c0000005` is returning access violation not command missing for me.
But I've no idea what happened. I restarted the build.

**Comment by mariusvniekerk** [comment]
i've restarted it twice with the same result :D

**Comment by mbargull** [comment]
Doesn't really help, but just for confirmation:
Page 387 in https://winprotocoldoc.blob.core.windows.net/productionwindowsarchives/MS-ERREF/%5bMS-ERREF%5d.pdf :
> 0xC0000005
> STATUS_ACCESS_VIOLATION
> The instruction at 0x%08lx referenced memory at 0x%08lx. The memory could not be %s.

**Comment by xhochy** [comment]
The main difference between master and the PR is the different Python version but all that changed is https://github.com/conda-forge/python-feedstock/pull/400/files

**Comment by xhochy** [comment]
It's passing locally for 😭

**Comment by mariusvniekerk** [comment]
should we try just running the bootstrap twice?
logging output looks really similar

**Comment by mariusvniekerk** [comment]
and that pass was with python buildno:2

**Comment by mbargull** [comment]
@mariusvniekerk, I can't follow.

**Comment by mbargull** [comment]
The current run seems to run through.
Let's file it under "temp. Azure issue" for now :shrug:.
